"""remove price per month column from promotion

Revision ID: 0aa08387b033
Revises: 7d7ea1f18330
Create Date: 2024-09-09 20:21:30.674849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa08387b033'
down_revision: Union[str, None] = '7d7ea1f18330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'price_per_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('price_per_month', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
