"""Add the discount column to promotions

Revision ID: 7d7ea1f18330
Revises: 5c6acf8e584f
Create Date: 2024-09-09 19:55:57.848058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7ea1f18330'
down_revision: Union[str, None] = '5c6acf8e584f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('promotions', 'installments',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'installments',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('promotions', 'discount')
    # ### end Alembic commands ###
