"""Updated cascading delete behavior for student enrollment

Revision ID: c0ed1e338454
Revises: 7a038fca9b48
Create Date: 2024-09-09 19:22:45.954330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ed1e338454'
down_revision: Union[str, None] = '7a038fca9b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('levels_program_id_fkey', 'levels', type_='foreignkey')
    op.create_foreign_key(None, 'levels', 'programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.add_column('promotions', sa.Column('general_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('promotions', sa.Column('settlements', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_constraint('promotions_program_id_fkey', 'promotions', type_='foreignkey')
    op.create_foreign_key(None, 'promotions', 'programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('student_enrollments_student_id_fkey', 'student_enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'student_enrollments', 'students', ['student_id'], ['id'])
    op.drop_constraint('time_slots_program_id_fkey', 'time_slots', type_='foreignkey')
    op.create_foreign_key(None, 'time_slots', 'programs', ['program_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.create_foreign_key('time_slots_program_id_fkey', 'time_slots', 'programs', ['program_id'], ['id'])
    op.drop_constraint(None, 'student_enrollments', type_='foreignkey')
    op.create_foreign_key('student_enrollments_student_id_fkey', 'student_enrollments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'promotions', type_='foreignkey')
    op.create_foreign_key('promotions_program_id_fkey', 'promotions', 'programs', ['program_id'], ['id'])
    op.drop_column('promotions', 'settlements')
    op.drop_column('promotions', 'general_fee')
    op.drop_constraint(None, 'levels', type_='foreignkey')
    op.create_foreign_key('levels_program_id_fkey', 'levels', 'programs', ['program_id'], ['id'])
    # ### end Alembic commands ###
